name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout Scryer Prolog
        uses: actions/checkout@v4
        with:
          repository: mthom/scryer-prolog
          path: scryer-prolog
      - name: Compile Scryer Prolog
        run: cargo build --release
        working-directory: scryer-prolog
      - name: Install Scryer Prolog
        run: sudo cp scryer-prolog/target/release/scryer-prolog /usr/bin/scryer-prolog
      - name: Execute tests
        run: make test
